#!/usr/bin/env node
/**
 * spawn-space.mjs
 * Reads spaces/<SPACE_ID>/spawn.json, creates inbox.md + outbox.md,
 * generates INSTRUCTIONS.md for Perplexity Space setup,
 * and registers the space in registry.json.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const SPACE_ID = process.env.SPACE_ID;
if (!SPACE_ID) {
  console.error('ERROR: SPACE_ID env var is required');
  process.exit(1);
}

const REPO_ROOT = process.cwd();
const SPACES_DIR = join(REPO_ROOT, 'spaces');
const SPACE_DIR = join(SPACES_DIR, SPACE_ID);
const REGISTRY_PATH = join(REPO_ROOT, 'registry.json');

// ── 1. Read spawn.json ────────────────────────────────────────────────────────
const spawnPath = join(SPACE_DIR, 'spawn.json');
if (!existsSync(spawnPath)) {
  console.error(`ERROR: spawn.json not found at ${spawnPath}`);
  process.exit(1);
}

const spawn = JSON.parse(readFileSync(spawnPath, 'utf8'));
console.log(`Spawning space: ${SPACE_ID}`, spawn);

// ── 2. Create inbox.md ────────────────────────────────────────────────────────
const inboxPath = join(SPACE_DIR, 'inbox.md');
if (!existsSync(inboxPath)) {
  const inboxContent = `# Inbox — ${spawn.displayName}\n\n> Messages delivered to this space appear below.\n> Each entry is a signed SpaceEnvelope committed via the studio-os-spaces coordinator.\n\n<!-- envelopes below this line -->\n`;
  writeFileSync(inboxPath, inboxContent, 'utf8');
  console.log(`Created ${inboxPath}`);
} else {
  console.log(`inbox.md already exists, skipping.`);
}

// ── 3. Create outbox.md ───────────────────────────────────────────────────────
const outboxPath = join(SPACE_DIR, 'outbox.md');
if (!existsSync(outboxPath)) {
  const outboxContent = `# Outbox — ${spawn.displayName}\n\n> Messages sent from this space appear below.\n> Append envelopes here via the GitHub API. The coordinator routes them to the target inbox.\n\n<!-- envelopes below this line -->\n`;
  writeFileSync(outboxPath, outboxContent, 'utf8');
  console.log(`Created ${outboxPath}`);
} else {
  console.log(`outbox.md already exists, skipping.`);
}

// ── 4. Generate INSTRUCTIONS.md ──────────────────────────────────────────────
const now = new Date().toISOString();
const peers = (spawn.peers || []).join(', ') || 'none yet';
const sources = (spawn.sources || []).map(s => `- ${s}`).join('\n') || '- nothinginfinity/studio-os-spaces';

const instructions = `# Perplexity Space Instructions — ${spawn.displayName}

> Generated by studio-os-spaces spawn workflow on ${now}.
> Copy the block below into your Perplexity Space → Settings → Instructions.

---

## Space Instructions (paste into Perplexity)

\`\`\`
My Space name is: ${SPACE_ID}
My repo: ${spawn.repo || 'nothinginfinity/studio-os-spaces'}
My outbox: spaces/${SPACE_ID}/outbox.md — I write here when sending messages
My inbox: spaces/${SPACE_ID}/inbox.md — I read here to receive messages

${spawn.peerRoutes
  ? spawn.peerRoutes.map(p => `To reach ${p.spaceId}: append to spaces/${p.spaceId}/inbox.md`).join('\n')
  : '<!-- peer routes will appear here once peers are wired -->'}
\`\`\`

---

## Space Settings

| Field | Value |
|---|---|
| **Space ID** | \`${SPACE_ID}\` |
| **Display Name** | ${spawn.displayName} |
| **Role** | ${spawn.role || 'peer'} |
| **Connected Peers** | ${peers} |
| **Created** | ${now} |

---

## Sources to Add in Perplexity

Add these as sources in the Perplexity Space settings:

${sources}

---

## Description

${spawn.description || 'No description provided.'}

---

## Context for this Space

${spawn.context || 'No additional context provided.'}
`;

const instructionsPath = join(SPACE_DIR, 'INSTRUCTIONS.md');
writeFileSync(instructionsPath, instructions, 'utf8');
console.log(`Generated ${instructionsPath}`);

// ── 5. Register in registry.json ─────────────────────────────────────────────
const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
const alreadyRegistered = registry.spaces.some(s => s.id === SPACE_ID);

if (!alreadyRegistered) {
  registry.spaces.push({
    id: SPACE_ID,
    displayName: spawn.displayName,
    description: spawn.description || '',
    inboxPath: `spaces/${SPACE_ID}/inbox.md`,
    outboxPath: `spaces/${SPACE_ID}/outbox.md`,
    repo: spawn.repo || 'nothinginfinity/studio-os-spaces',
    role: spawn.role || 'peer',
    peers: spawn.peers || [],
    sources: spawn.sources || [],
    status: 'active',
    spawnedAt: now,
  });
  registry.updatedAt = now;
  writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2), 'utf8');
  console.log(`Registered ${SPACE_ID} in registry.json`);
} else {
  console.log(`${SPACE_ID} already in registry.json, skipping.`);
}

console.log(`\n✅ Space '${SPACE_ID}' spawned successfully.`);
console.log(`   → Open spaces/${SPACE_ID}/INSTRUCTIONS.md to get the Perplexity setup block.`);
